local boss_list = {
    -- "DEERCLOPS_HEALTH",
     --"BEARGER_HEALTH",
     --"ANTLION_HEALTH",
     --"SPIDERQUEEN_HEALTH",
     --"SHARKBOI_HEALTH",
 
     "EYEOFTERROR_HEALTH",
     "DRAGONFLY_HEALTH",
     "BEEQUEEN_HEALTH",
     "TOADSTOOL_DARK_HEALTH",
 
     "MINOTAUR_HEALTH",
     "DAYWALKER_HEALTH",
     "CORRUPT_HEART_HEALTH",
 
     "KLAUS_HEALTH",
     
     --"MUTATED_DEERCLOPS_HEALTH",
     --"MUTATED_BEARGER_HEALTH",
     --"MUTATED_WARG_HEALTH",
 
     "STALKER_ATRIUM_HEALTH",
     "STALKER_ATRIUM_PHASE2_HEALTH",
     "STALKER_ATRIUM_PHASE3_HEALTH",
     
     "ANCIENT_HULK_HEALTH",
     "IRONLORD_HEALTH",
     "TWIN1_HEALTH",
     "TWIN2_HEALTH",
     "ALTERGUARDIAN_PHASE1_HEALTH",
     "ALTERGUARDIAN_PHASE1_SHIELDTRIGGER",
     "ALTERGUARDIAN_PHASE2_MAXHEALTH",
     "ALTERGUARDIAN_PHASE2_STARTHEALTH",
     "ALTERGUARDIAN_PHASE3_MAXHEALTH",
     "ALTERGUARDIAN_PHASE3_STARTHEALTH",
 }


local hp_rate = GetModConfigData("bosshp")

for i,v in ipairs(boss_list) do
    TUNING[v] = hp_rate*TUNING[v]
end
