---------升级--------------
GLOBAL.UPGRADETYPES.IRON_SOUL="IRON_SOUL"
GLOBAL.UPGRADETYPES.INSIGHT_SOUL="INSIGHT_SOUL"


---------修补---------------




--MATERIALS.EPIC = "epic"
GLOBAL.MATERIALS.PURE = "pure"
GLOBAL.FORGEMATERIALS.IRON = "iron"
GLOBAL.EQUIPMENTSETNAMES.ANCIENT = "ancient"

GLOBAL.FUELTYPE.PURE = "moon_pure"

--TOOLACTIONS.ACTIVATE = true
GLOBAL.LOCKTYPE.LUNAR = "lunar"



