local STRINGS = GLOBAL.STRINGS


STRINGS.NAMES.OBSIDIANFIREPIT = "obsidian pit"
STRINGS.NAMES.SPEAR_OBSIDIAN="obsidian spear"
STRINGS.NAMES.AXEOBSIDIAN=" obsidian axe"
STRINGS.NAMES.ARMOROBSIDIAN=" obsidian armor"
STRINGS.NAMES.OBSIDIAN="obsidian"
STRINGS.NAMES.LAVAPOOL_CS="lavapool"
STRINGS.NAMES.DRAGOON_CS="dragoon"
STRINGS.NAMES.DRAGOONHEART="dragoon heart"
STRINGS.NAMES.DRAGOONEGG_CS="dragoon egg"
STRINGS.NAMES.OBSIDIAN_HAT="dragon hat"
STRINGS.NAMES.VOLCANOSTAFF="volcano staff"

STRINGS.NAMES.SHADOWEYETURRET = "ruins eyeturrent"
STRINGS.NAMES.ANCIENT_SCANNER = "shadow scout"
STRINGS.NAMES.SHADOWDRAGON = "nightmare dragon"
STRINGS.NAMES.LEECHTERROR = "claw of shadow"
STRINGS.NAMES.SMALL_LEECHTERROR = "claw of shadow"
STRINGS.NAMES.SPIDER_ROBOT="wreck of robots"
STRINGS.NAMES.MAZE_KEY = "maze key"

STRINGS.NAMES.QUAKER = "quaker"
STRINGS.NAMES.SUPERBOAT_KIT = "ironclad kit"
STRINGS.NAMES.SUPERBOAT = "ironclad"
STRINGS.NAMES.ANTIDOTE = "universal antidote"


STRINGS.NAMES.CORRUPT_HEART = "corrupt heart"
STRINGS.NAMES.MOON_LIGHTNING2 = "moon lightning"
STRINGS.NAMES.LUNARTHRALL_PLANT_QUEEN = "brightshade queen"
STRINGS.NAMES.LUNARLIGHT = "brilliance light"

STRINGS.NAMES.ANCIENT_HULK="iron hulk"
STRINGS.NAMES.ANCIENT_HULK_MINE = "mine"


STRINGS.NAMES.IRON_MINE = "auric iron mine"
STRINGS.NAMES.CS_SHADOWTHRONE = "nightmare throne"
STRINGS.NAMES.ABYSS_ENDSWELL = "ending well"

STRINGS.NAMES.CS_IRON = "auric iron"
STRINGS.NAMES.CS_INFUSED_IRON = "constant stone"
STRINGS.NAMES.ARMORABYSS = "abyss cloak"
STRINGS.NAMES.SWORD_LUNARBLAST="lunarblast blade"
STRINGS.NAMES.STAFF_LUNARBLAST="lunarblast staff"
STRINGS.NAMES.LASER_GENERATOR = "steel gloves"
STRINGS.NAMES.LASER_CANNON = "laser cannon"
STRINGS.NAMES.ABYSS_EYE = "∆∞?Ey?"
STRINGS.NAMES.CS_WATERDROP = "constant water"
STRINGS.NAMES.ABYSS_FLOWER = "constant flower"
STRINGS.NAMES.CS_VOID_BAG = "voidbag"
STRINGS.NAMES.CS_DREADSWORD = "dreadsword"
STRINGS.NAMES.NORTHPOLE = "northpole"
STRINGS.NAMES.ARMOR_ANCIENT = "auric armor"
STRINGS.NAMES.HAT_ANCIENT = "auric hat"
STRINGS.NAMES.SWORD_ANCIENT = "constant blade"
STRINGS.NAMES.TRUE_VOIDCLOTH_SCYTHE = "life hunter"


STRINGS.NAMES.INSIGHT_SOUL="insight soul"
STRINGS.NAMES.IRON_SOUL="iron soul"
STRINGS.NAMES.DEMON_SOUL="demon soul"
STRINGS.NAMES.SHADOW_SOUL="shadow soul"

STRINGS.NAMES.SHADOWFIREBALL = "hell falling"

STRINGS.NAMES.ABYSS_KNIGHT = "abyss knight"
STRINGS.NAMES.ABYSS_THRALL = "ancient herald"
STRINGS.NAMES.DREADDRAGON = "dread dragon"
STRINGS.NAMES.ABYSS_HOPLITE = "abyss hoplite"
STRINGS.NAMES.DARK_ENERGY = "dark energy"




STRINGS.NAMES.POISON = "poison"
STRINGS.NAMES.POISON_2 = ""
STRINGS.NAMES.CURSE_FIRE = "cursed fire"
STRINGS.NAMES.WEAK = "weak"
STRINGS.NAMES.VULNERABLE = "vulnerable"
STRINGS.NAMES.FOOD_SICK = "food sick"
STRINGS.NAMES.EXHAUSTION = "exhaustion"
STRINGS.NAMES.BUFF_FAST = "fast"
STRINGS.NAMES.BUFF_WARM = "warm"
STRINGS.NAMES.BUFF_INSIGHT = "insight"
STRINGS.NAMES.BUFF_IRON = "armored"
STRINGS.NAMES.BUFF_ATTACK = "damage increase"
STRINGS.NAMES.BUFF_PLAYERABSORPTION = "garlic power"
STRINGS.NAMES.BUFF_WORKEFFECTIVENESS = "efficient"
STRINGS.NAMES.BUFF_MOISTUREIMMUNITY = "dry"
STRINGS.NAMES.BUFF_ELECTRICATTACK = "elctrify"
STRINGS.NAMES.BUFF_SLEEPRESISTANCE = "sleep resistance"
STRINGS.NAMES.HEALTHREGENBUFF = "life regen"
STRINGS.NAMES.MOON_CURSE = "moon curse"
STRINGS.NAMES.SOLAR_FIRE = "solar blast"

STRINGS.NAMES.BOSSRUSH_MANAGER = "void gate"
STRINGS.NAMES.VOID_LIGHT = "void light"
STRINGS.NAMES.VOID_KEY = "void key"
STRINGS.NAMES.PLANAR_KEY = "planar key"
STRINGS.NAMES.VOIDKEYHOLE = "void gate"

STRINGS.NAMES.IRONLORD = "possessed armor"
STRINGS.NAMES.IRONLORD_DEATH = "debris"

STRINGS.NAMES.CALAMITYEYE = "Caiamitas"
STRINGS.NAMES.VULNERABILITY_HEX = "Brimstone Flames"
STRINGS.NAMES.SOUL_SEEKER = "soul seeker"
STRINGS.NAMES.HELLBLASTS = "hell skull"
STRINGS.NAMES.SOUL_BREAK = "soul break"



STRINGS.RECIPE_DESC.ARMORABYSS="通往深层维度的通道"
STRINGS.RECIPE_DESC.OBSIDIANFIREPIT="最暴烈的火焰"
STRINGS.RECIPE_DESC.ARMOROBSIDIAN="摸上去很热"
STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN="给你的矛来点火"
STRINGS.RECIPE_DESC.AXEOBSIDIAN="像普通的斧子一样，只是更热"
STRINGS.RECIPE_DESC.OBSIDIAN="蕴含着最纯粹的火焰"
STRINGS.RECIPE_DESC.QUAKER="制造地震波"
STRINGS.RECIPE_DESC.OBSIDIAN_HAT="像巨龙一样冲锋"
STRINGS.RECIPE_DESC.SUPERBOAT_KIT="征服大海"
STRINGS.RECIPE_DESC.ANTIDOTE="解除任何中毒"
STRINGS.RECIPE_DESC.VOLCANOSTAFF="让火焰净化一切"
STRINGS.RECIPE_DESC.LUNARLIGHT="纯粹之光，驱散邪恶"

STRINGS.RECIPE_DESC.SWORD_LUNARBLAST = "发射月亮剑气"
STRINGS.RECIPE_DESC.STAFF_LUNARBLAST = "用月能制造爆炸"
STRINGS.RECIPE_DESC.NORTHPOLE = "冰冻三尺"
STRINGS.RECIPE_DESC.TRUE_VOIDCLOTH_SCYTHE = "收割灵魂"
STRINGS.RECIPE_DESC.LASER_GENERATOR = "足以击碎绝望"
STRINGS.RECIPE_DESC.CS_INFUSED_IRON = "永恒之力蕴含其中"
STRINGS.RECIPE_DESC.CS_VOID_BAG = "连通暗影维度"

STRINGS.RECIPE_DESC.CS_DREADSWORD = "为敌人带来绝望"
STRINGS.RECIPE_DESC.SWORD_ANCIENT="蕴含摧毁位面的力量"
STRINGS.RECIPE_DESC.HAT_ANCIENT = "守护你的灵魂"
STRINGS.RECIPE_DESC.ARMOR_ANCIENT = "驱散暗影"
STRINGS.RECIPE_DESC.LASER_CANNON = "发射激光球"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORABYSS = "你正凝视着深渊"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NORTHPOLE = "纯洁无暇的冰晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDER_ROBOT = "现在它只想毁灭一切"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOON_CS = "可笑的生物，只剩下稀薄的巨龙血脉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONEGG_CS = "摧毁它！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORD_LUNARBLAST = "圣神之光猛烈燃烧！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRUE_STAFF_LUNARPLANT = "月能之力喷薄而出！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRUE_VOIDCLOTH_SCYTHE = "阴冷之影蛊惑灵魂！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAPOOL_CS = "蕴含着火焰精华"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEAR_OBSIDIAN = "以一己之力戳翻TMD整个世界！！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT= "璀璨夺目"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AXEOBSIDIAN = "樵夫，用它砍那棵树吧！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDER_ARMOROBSIDIAN = "其名唤可怖，乃众多激烈之物交织而成"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGOONHEART = "它仍在跳动，就像我们仍在负重前行"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUAKER = "轰隆隆！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN_HAT = "感觉...脑袋热热的"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ABYSS_KNIGHT = "只有最污秽的魔法才能制造出这等可怖的生物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNIGHTMARE = "只有最污秽的魔法才能制造出这等可怖的生物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CS_IRON = "这矿石蕴含的能量...再看一眼就会爆炸"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CS_INFUSED_IRON = "我将披靡天下"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWEYETURRET = "它的凝视如雕像般...遥远,平静,冷峻"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANCIENT_SCANNER = "神风特工队？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWDRAGON = "好可爱吖，都这么夸你了，可以不要打我吗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "巨龙的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LASER_GENERATOR = "力拔山兮气盖世"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ABYSS_ENDSWELL = "你在渴求什么？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRON_MINE = "一路火花带闪电，碰一碰就来世见"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPER_COOKPOT = "永恒牌的高压锅，煮什么都不嫌多"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DREADDRAGON = "红眼病怕看不清，莎*爱思滴眼睛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOSSRUSH_MANAGER = "事已至此，我们没有退路可言"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ABYSS_FLOWER = "病即消灭,不老不死"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CS_WATERDROP = "敬神圣水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOR_ANCIENT = "屠戮神金甲！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HAT_ANCIENT = "金朔暗影盔！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLCANOSTAFF = "煌煌天威！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTIDOTE = "它包治百病"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPERBOAT = "乘风破浪！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPERBOAT_KIT = "我即将扬帆远航！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CS_VOID_BAG = "真神奇，这里的东西都去哪里了？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDER_ROBOT = "它迷失了，永生永世的徘徊在这里"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORRUPT_HEART = "它吞噬了世间的一切光明"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUNARTHRALL_PLANT_QUEEN = "南方大植物！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUNARLIGHT = "它的火焰能够驱散那些虚影！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ABYSS_THRALL = "末世将至"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANCIENT_HULK = "恐怖的机器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRON_SOUL = "躁动不安"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.INSIGHT_SOUL = "看穿一切的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOW_SOUL = "原初的暗影"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISSURE_ABYSS = "来自深渊"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CS_SHADOWTHRONE = "只是个影子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CS_DREADSWORD = "暗影只是手段..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PLANAR_KEY = "一颗时空晶体，记录着各个位面的坐标"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOID_KEY = "留有某个未知存在的痕迹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOIDKEYHOLE = "激活它也许是个错误"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOID_LIGHT = "永恒地燃烧着"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.IRONLORD_DEATH = "它的内在是空虚的"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_FAST = "我的脚步无比轻快"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_FAST = "我的脚步变得沉重"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_WARM = "我不再惧怕寒冷"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_WARM = "哦，好冷！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_INSIGHT = "世界对我不再有秘密"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_INSIGHT = "我的视野变得模糊"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_IRON = "软弱的攻击伤不了我"


--STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.BUILD.DONT_DESERVE = "不配"
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.USEKLAUSSACKKEY.NOPOWER = "It needs power"
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.REPAIR.WRONG_GEM_COLOUR = "wrong type"
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.USEKLAUSSACKKEY.COOLDOWN = "in cooldown"



STRINGS.UI.BUFFPANEL_TIP = "Right-click and drag"
STRINGS.FIRERAIN_COMING = "the air is getting hot"
STRINGS.FIRE_ERA_COME = "the ancient dragon and fire revived"
STRINGS.WAGSTAFF_NPC_GET_IRONSOUL = {"Excellent! It will greatly promote my robot research"}

STRINGS.ACTIONS.CASTAOE.RUINS_BAT = "parry"
STRINGS.ACTIONS.CASTAOE.CS_DREADSWORD = "parry"
STRINGS.ACTIONS.CASTAOE.LASER_CANNON = "shoot"
STRINGS.ACTIONS.TOWNPORTAL = "activate townportal"
STRINGS.ACTIONS.LUNGE = "lunge"
STRINGS.ACTIONS.SHADOWDODGE = "dodge"

STRINGS.BOSSRUSH = 
{
    "你享受地狱之旅吗",
    "无足轻重的表现",     --2
    "有趣，很少有人能击败这些巨兽",   --3
    "你是一位可敬的战士",  --4
    "你的最终试炼开始了",      --5
    "奖励？继续前进吧，"
}


