local STRINGS=STRINGS
STRINGS.NAMES.ARMORVORTEXCLOAK = "漩涡斗篷" -- 设置物体在游戏中显示的名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORVORTEXCLOAK = "你正凝视着深渊" -- 物体的检查描述
STRINGS.NAMES.ANCIENT_HULK="远古铁巨人"
STRINGS.NAMES.ANCIENT_HULK_ORB="等离子光球"
STRINGS.NAMES.ANCIENT_HULK_MINE="地雷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANCIENT_HULK = "远古文明的终极兵器"
STRINGS.NAMES.SHADOWEYETURRET="远古哨兵"
STRINGS.NAMES.ANCIENT_SCANNER="暗影侦察者"
STRINGS.NAMES.SHADOWDRAGON="恐惧之龙"
STRINGS.NAMES.TRUE_SWORD_LUNARPLANT="真·亮茄剑"
STRINGS.NAMES.TRUE_STAFF_LUNARPLANT="真·亮茄杖"
STRINGS.NAMES.LASER_SPARK="球状闪电"
STRINGS.NAMES.OBSIDIANFIREPIT="黑曜石火坑"
STRINGS.NAMES.SPEAR_OBSIDIAN="黑曜石长矛"
STRINGS.NAMES.AXEOBSIDIAN="黑曜石斧"
STRINGS.NAMES.ARMOROBSIDIAN="黑曜石护甲"
STRINGS.NAMES.OBSIDIAN="黑曜石"
STRINGS.NAMES.LAVAPOOL="火坑"
STRINGS.NAMES.DRAGOON="暴虐龙人"
STRINGS.NAMES.DRAGOONHEART="龙心"
STRINGS.NAMES.DRAGOONEGG="龙蛋"
STRINGS.NAMES.INSIGHT_SOUL="视域之魂"
STRINGS.NAMES.IRON_SOUL="钢铁之魂"
STRINGS.NAMES.DEMON_SOUL="恶魔之魂"
STRINGS.NAMES.QUAKER="地震器"
STRINGS.NAMES.OBSIDIAN_HAT="龙鳞头盔"
STRINGS.NAMES.LUNAR_BLAST="月能审判"
STRINGS.NAMES.LEECHTERROR="暗影之爪"
STRINGS.NAMES.SMALL_LEECHTERROR="暗影之爪"
STRINGS.NAMES.POISON="中毒"
STRINGS.NAMES.POISON_2="剧毒"
STRINGS.NAMES.CURSE_FIRE="咒火"
STRINGS.NAMES.WEAK="虚弱"
STRINGS.NAMES.VULNERABLE="易伤"
STRINGS.NAMES.FOOD_SICK="呕吐"
STRINGS.NAMES.EXHAUSTION="凋零"

STRINGS.NAMES.LUNARTHRALL_PLANT_QUEEN="至尊亮茄"
STRINGS.NAMES.ALTER_LIGHT="天界之光"
STRINGS.NAMES.VOLCANOSTAFF="阳炎之怒"
STRINGS.NAMES.LUNARLIGHT="辉煌灯柱"

STRINGS.NAMES.SUPERBOAT_KIT="铁甲船套装"
STRINGS.NAMES.SUPERBOAT="铁甲船"
STRINGS.NAMES.ANTIDOTE="万能解毒剂"

STRINGS.NAMES.SHADOW_MFZ="至尊猴王"
STRINGS.NAMES.SPIDER_ROBOT="遗迹守卫"
STRINGS.NAMES.CORRUPT_HEART="腐化之心"

STRINGS.NAMES.NORTHPOLE = "北极"
STRINGS.NAMES.ARMOR_ANCIENT = "古圣金甲"
STRINGS.NAMES.HAT_ANCIENT = "古圣金头盔"
STRINGS.NAMES.SWORD_ANCIENT = "永恒之锋"
STRINGS.NAMES.TRUE_VOIDCLOTH_SCYTHE = "死亡收割"
STRINGS.NAMES.BOSSRUSH = ""
STRINGS.NAMES.VOID_KEY = "维度钥匙"

STRINGS.RECIPE_DESC.ARMORVORTEXCLOAK="通往深层维度的通道"
STRINGS.RECIPE_DESC.OBSIDIANFIREPIT="最暴烈的火焰"
STRINGS.RECIPE_DESC.ARMOROBSIDIAN="摸上去很热"
STRINGS.RECIPE_DESC.SPEAR_OBSIDIAN="给你的矛来点火"
STRINGS.RECIPE_DESC.AXEOBSIDIAN="像普通的斧子一样，只是更热"
STRINGS.RECIPE_DESC.OBSIDIAN="蕴含着最纯粹的火焰"
STRINGS.RECIPE_DESC.QUAKER="制造地震波"
STRINGS.RECIPE_DESC.OBSIDIAN_HAT="像巨龙一样冲锋"
STRINGS.RECIPE_DESC.SUPERBOAT_KIT="征服大海"
--STRINGS.RECIPE_DESC.LUNAR_BLAST="用纯粹的月能湮灭一切"
STRINGS.RECIPE_DESC.ANTIDOTE="解除任何中毒"
STRINGS.RECIPE_DESC.VOLCANOSTAFF="让火焰净化一切"
STRINGS.RECIPE_DESC.LUNARLIGHT="纯粹之光，驱散邪恶"

STRINGS.RECIPE_DESC.TRUE_SWORD_LUNARPLANT = "发射穿透剑气"
STRINGS.RECIPE_DESC.TRUE_STAFF_LUNARPLANT = "用月能制造爆炸"
STRINGS.RECIPE_DESC.NORTHPOLE = "冰冻三尺"
STRINGS.RECIPE_DESC.TRUE_VOIDCLOTH_SCYTHE = "收割灵魂"

STRINGS.RECIPE_DESC.SWORD_ANCIENT="蕴含摧毁位面的力量"
STRINGS.RECIPE_DESC.HAT_ANCIENT="足以抵御神明的攻击"
STRINGS.RECIPE_DESC.ARMOR_ANCIENT="闪耀着奇异的光芒"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDER_ROBOT="现在它只想毁灭一切"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_FAST = "我的脚步无比轻快"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_FAST = "我的脚步变得沉重"

STRINGS.ACTIONS.CASTAOE.RUINS_BAT="格挡"



STRINGS.WHY_YOU_HERE={"你怎么还在这里"}
STRINGS.I_WILL_WIN={"会赢的","哼，想逃？"}
STRINGS.YOU_PASS_THE_EXAME={"你通过了考验"}
STRINGS.BOSSRUSH = 
{
    "看来大门被重启了",
    "能到达这里，你的力量值得尊敬",
    "不过还远远不够",
    "展示你的极限吧",
    "准备接受考验",   --1
    "热身结束",     --2
    "挑战才刚刚开始",   --3
    "也许...真的可以阻止它们",  --4
    "你的最终试炼开始了",      --5
    "一份薄礼，它会派上用场的"
}