local bossrush_tuning = 
{
	SHARKBOI_WALKSPEED = 6,
	SHARKBOI_RUNSPEED = 12,
	SHARKBOI_FINSPEED = 8,
	SHARKBOI_ATTACK_PERIOD = 2,
	SHARKBOI_WATER_WALKSPEED = 4,
	SHARKBOI_WATER_RUNSPEED = 14,

	MUTATED_DEERCLOPS_ATTACK_PERIOD = 2,
	MUTATED_DEERCLOPS_COMBO_ATTACK_PERIOD = 3,
}

return bossrush_tuning