local bossrush_tuning = 
{	
	DEFAULT_HIT_RECOVERY = 20,
	DRAGONFLY_FLYING_HIT_RECOVERY = 20,
	KLAUS_HIT_RECOVERY = 50,
	ANTLION_HIT_RECOVERY = 50,
	STALKER_HIT_RECOVERY = 60,
	DAYWALKER_HIT_RECOVERY = 50,
	BEEQUEEN_HIT_RECOVERY = 100,

	
	BEARGER_ATTACK_PERIOD = 1,
	BEARGER_CALM_WALK_SPEED = 2,
    BEARGER_ANGRY_WALK_SPEED = 8,
    BEARGER_RUN_SPEED = 20,
	BEARGER_MELEE_RANGE = 10,

	ANTLION_MAX_ATTACK_PERIOD = 2,
    ANTLION_MIN_ATTACK_PERIOD = 1,
	ANTLION_CAST_RANGE = 25,
	ANTLION_CAST_MAX_RANGE = 30,

	SPIDERQUEEN_WALKSPEED = 6,
	SPIDERQUEEN_ATTACKPERIOD = 1,
	SPIDER_WARRIOR_ATTACK_PERIOD = 0.5,
	SPIDER_SPITTER_ATTACK_PERIOD = 0.5,
	SPIDER_WARRIOR_ATTACK_RANGE = 14,
	SPIDER_WARRIOR_RUN_SPEED = 8,
	SPIDER_SPITTER_ATTACK_RANGE = 20,
	SPIDER_SPITTER_DAMAGE_MELEE = 50,
	SPIDER_WARRIOR_DAMAGE = 80,

	DEERCLOPS_ATTACK_PERIOD = 0.5,
	DEERCLOPS_ATTACK_RANGE = 12,

	SHARKBOI_WALKSPEED = 6,
	SHARKBOI_RUNSPEED = 10,
	SHARKBOI_FINSPEED = 14,
	SHARKBOI_ATTACK_PERIOD = 2,
	SHARKBOI_WATER_WALKSPEED = 4,
	SHARKBOI_WATER_RUNSPEED = 14,
	SHARKBOI_MELEE_RANGE = 10,
	SHARKBOI_ATTACK_RANGE = 12,

	EYEOFTERROR_CHARGESPEED = 22,

	DRAGONFLY_ATTACK_PERIOD = 2,
	DRAGONFLY_FIRE_ATTACK_PERIOD = 1,
	DRAGONFLY_TRANSFORM = 0.9,
	DRAGONFLY_STUN = 250000,
	DRAGONFLY_FIRE_SPEED = 10,
	DRAGONFLY_FREEZE_THRESHOLD = 40,
	DRAGONFLY_ENRAGED_FREEZE_THRESHOLD = 120,
	DRAGONFLY_RESET_DIST = 80,

	DRAGOON_DAMAGE = 200,


	BEEQUEEN_TOTAL_GUARDS = 16,
	BEEQUEEN_MIN_GUARDS_PER_SPAWN = 6,
    BEEQUEEN_MAX_GUARDS_PER_SPAWN = 8,
	BEEGUARD_SPEED = 7,
	BEEGUARD_DAMAGE = 100,
	BEEGUARD_DASH_SPEED = 12,
	
	TOADSTOOL_MUSHROOMSPROUT_CD = 25,
	TOADSTOOL_MUSHROOMSPROUT_CHOPS = 20,
	TOADSTOOL_SPEED_LVL =
        {
            [0] = 6,
            [1] = 8,
            [2] = 10,
            [3] = 11,
        },

	MINOTAUR_LEAP_CD = 1,

	MINOTAUR_WALK_SPEED = 8,
	MINOTAUR_RUN_SPEED = 20,
	MINOTAUR_STUNTIME = 5,

	DAYWALKER_WALKSPEED = 4,
	DAYWALKER_RUNSPEED = 8,
	
	KLAUS_ATTACK_PERIOD = 0.5,
	KLAUS_SPEED = 5,
	DEER_WALK_SPEED = 6,
    DEER_RUN_SPEED = 12,
	DEER_GEMMED_CAST_RANGE = 22,
    DEER_GEMMED_CAST_MAX_RANGE = 25,

	CORRUPT_HEART_RANGESQ = 24*24,
	
	MUTATED_DEERCLOPS_ATTACK_PERIOD = 1,
	MUTATED_DEERCLOPS_COMBO_ATTACK_PERIOD = 1,

	MUTATED_BEARGER_ATTACK_RANGE = 10,
	MUTATED_BEARGER_ATTACK_PERIOD = 1,

	HOUND_DAMAGE = 100,
	ICEHOUND_DAMAGE = 150,
	HOUND_ATTACK_PERIOD = 1,
	MOONHOUND_ATTACK_PERIOD = 1,

	DAYWALKER2_TACKLE_SPEED = 14,
	DAYWALKER2_ATTACK_PERIOD = { min = 1.5, max = 2 },
	DAYWALKER2_CANNON_NEAR_DAMAGE_MULT = 2.5, --mult for ALTERGUARDIAN_PHASE3_LASERDAMAGE
	DAYWALKER2_CANNON_FAR_DAMAGE_MULT = 1,
	
	STALKER_CHANNELERS_COUNT = 16,
	STALKER_FEAST_HEALING = 2000,
	STALKER_MINDCONTROL_RANGE = 20,
	STALKER_MINDCONTROL_DURATION = 5,
	STALKER_SNARE_RANGE = 25,
    STALKER_SNARE_MAX_RANGE = 30,
    STALKER_SNARE_TIME = 10,


	TWIN1_CHARGESPEED = 20,
	TWIN2_CHARGESPEED = 22,
	TWIN_CHARGE_FLAME_SPEED = 14,
	TWIN2_MOUTH_CHARGESPEED = 28,

	ALTERGUARDIAN_PHASE1_ROLLDAMAGE = 300,
	ALTERGUARDIAN_PHASE1_ATTACK_PERIOD = 2,
	
	ALTERGUARDIAN_PHASE2_DAMAGE = 400,
	ALTERGUARDIAN_PHASE2_SPIKEDAMAGE = 200,
	ALTERGUARDIAN_PHASE3_LASERDAMAGE = 500,
	ALTERGUARDIAN_PHASE3_TRAP_GROGGINESS = 5,
	ALTERGUARDIAN_PHASE3_TRAP_KNOCKOUTTIME = 10,

	ALTERGUARDIAN_PHASE2_SPIN2CD= 5,
	ALTERGUARDIAN_PHASE2_LIGHTNINGCOOLDOWN = 10,
	ALTERGUARDIAN_PHASE2_DEADSPIN_SPEED = 22,

	ALTERGUARDIAN_PHASE3_ERASERCOOLDOWN = 30,
	ALTERGUARDIAN_PHASE3_FLAMECOOLDOWN  = 20,
	ALTERGUARDIAN_PHASE3_ATTACK_PERIOD = 1,
	ALTERGUARDIAN_PHASE3_TRAP_CD = 20,
	ALTERGUARDIAN_PHASE3_SUMMONCOOLDOWN = 15,
	GESTALTGUARD_DAMAGE = 500,
}

return bossrush_tuning