local seg_time = 30
local total_day_time = seg_time*16

local TUNING = TUNING

-----------------------------
-------------原版内容改动
-----------------------------


--克盾
TUNING.SHIELDOFTERROR_ARMOR = 840


--启迪之冠
TUNING.SANITY_BECOME_ENLIGHTENED_THRESH = 150/200
TUNING.SANITY_LOSE_ENLIGHTENMENT_THRESH = 145/200


--寒冰护符
TUNING.BLUEAMULET_FUEL = total_day_time


--亮茄套装
TUNING.ARMOR_LUNARPLANT = 1850
TUNING.ARMOR_LUNARPLANT_ABSORPTION = 0.9
TUNING.ARMOR_LUNARPLANT_HAT = 1260

--虚空套装
TUNING.ARMOR_VOIDCLOTH = 1600
TUNING.ARMOR_VOIDCLOTH_HAT = 1050
TUNING.ARMOR_VOIDCLOTH_SETBONUS_PLANARDAMAGE_MAX = 30
TUNING.ARMOR_VOIDCLOTH_SETBONUS_PLANARDAMAGE_MAX_HITS = 5
TUNING.ARMOR_VOIDCLOTH_SETBONUS_PLANARDAMAGE_DECAY_TIME = 5



--天体英雄
TUNING.ALTERGUARDIAN_PHASE1_MINROLLCOUNT = 12
TUNING.ALTERGUARDIAN_PHASE1_TARGET_DIST = 28
TUNING.ALTERGUARDIAN_PHASE1_ATTACK_PERIOD = 6


TUNING.ALTERGUARDIAN_PHASE2_SPIN_SPEED = 9
TUNING.ALTERGUARDIAN_PHASE2_TARGET_DIST = 36  --仇恨范围
TUNING.ALTERGUARDIAN_PHASE2_SPIKE_RANGE = 25
TUNING.ALTERGUARDIAN_PHASE2_ATTACK_PERIOD = 5
TUNING.ALTERGUARDIAN_PHASE2_SPIN_RANGE = 28 --攻击范围
--TUNING.ALTERGUARDIAN_PHASE2_SUMMONCOOLDOWN = 24.25
TUNING.ALTERGUARDIAN_PHASE2_SPIKECOOLDOWN = 40
TUNING.ALTERGUARDIAN_PHASE2_LIGHTNINGCOOLDOWN = 20
TUNING.ALTERGUARDIAN_PHASE2_LIGHTNING_DAMAGE = 180

--TUNING.ALTERGUARDIAN_PHASE2_SPINCD = 14.25
TUNING.ALTERGUARDIAN_PHASE2_SPIN2CD = 45
TUNING.ALTERGUARDIAN_PHASE2_DEADSPIN_SPEED = 16


TUNING.ALTERGUARDIAN_PHASE3_TARGET_DIST = 36  --仇恨
TUNING.ALTERGUARDIAN_PHASE3_TRAP_MAXRANGE = 5
TUNING.ALTERGUARDIAN_PHASE3_ATTACK_PERIOD = 4
TUNING.ALTERGUARDIAN_PHASE3_ATTACK_RANGE = 28  --攻击
TUNING.ALTERGUARDIAN_PHASE3_TRAP_LT = 40
TUNING.ALTERGUARDIAN_PHASE3_ERASERCOOLDOWN = 60
TUNING.ALTERGUARDIAN_PHASE3_FLAMECOOLDOWN = 50

--远古织影者
TUNING.STALKER_ATRIUM_PHASE3_HEALTH = 6000


--噩梦猪人
TUNING.DAYWALKER_HEALTH_REGEN = 25
TUNING.DAYWALKER_COMBAT_STALKING_HEALTH_REGEN = 20
TUNING.DAYWALKER_COMBAT_TIRED_HEALTH_REGEN = 25
TUNING.DAYWALKER_FATIGUE_TIRED = 5
TUNING.DAYWALKER_AGGRO_DIST = 30
TUNING.DAYWALKER_KEEP_AGGRO_DIST = 25


--岩浆虫
TUNING.LAVAE_HEALTH = 300
TUNING.DRAGONFLY_TRANSFORM = 0.3

--克眼
TUNING.EYEOFTERROR_HEALTH = 8000
TUNING.EYEOFTERROR_MINGUARDS_PERSPAWN = 4
TUNING.EYEOFTERROR_AOE_DAMAGE= 200
TUNING.EYEOFTERROR_AOERANGE = 4
TUNING.EYEOFTERROR_CHARGESPEED = 17
TUNING.EYEOFTERROR_MOUTHCHARGECD = 0.25*15
TUNING.EYEOFTERROR_CHARGECD = 0.5*7
TUNING.EYEOFTERROR_SPAWNCD = 12
TUNING.EYEOFTERROR_DAMAGE = 180
TUNING.EYEOFTERROR_MOUTH_MINGUARDS = 8
TUNING.EYEOFTERROR_ATTACKPERIOD = 2
TUNING.EYEOFTERROR_DEAGGRO_DIST = 36


--毒菌蟾蜍
TUNING.TOADSTOOL_HEALTH = 20000
TUNING.TOADSTOOL_DARK_HEALTH = 38000
TUNING.TOADSTOOL_SPEED_LVL =
{
    [0] = 1,
    [1] = 2,
    [2] = 3,
    [3] = 4,
}
TUNING.TOADSTOOL_MUSHROOMBOMB_COUNT_PHASE =
{
    [1] = 6,
    [2] = 7,
    [3] = 8,
}


--双子魔眼
TUNING.TWINS_RESET_DAY_COUNT = 4
TUNING.TWIN1_CHARGESPEED = 18
TUNING.TWIN2_CHARGESPEED = 20
TUNING.TWIN1_CHARGECD		= 12
TUNING.TWIN2_CHARGECD		= 12
TUNING.TWIN1_MOUTHCHARGECD	= 16
TUNING.TWIN2_MOUTHCHARGECD	= 10
TUNING.TWIN_CHARGE_FLAME_SPEED = 10
TUNING.TWIN2_MOUTH_CHARGESPEED = 22
TUNING.TWIN2_MOUTH_CHARGETIMEOUT = 0.8
TUNING.TWIN2_DAMAGE = 200
TUNING.TWIN1_DAMAGE = 200


--墨荒
TUNING.SHADOWTHRALL_AGGRO_RANGE = 25
TUNING.SHADOWTHRALL_HORNS_WALKSPEED = 6
TUNING.SHADOWTHRALL_HANDS_WALKSPEED = 6
TUNING.SHADOWTHRALL_WINGS_WALKSPEED = 7
TUNING.FUSED_SHADELING_AGGRO_RANGE = 25


TUNING.VOIDCLOTH_BOOMERANG_USES = 180

TUNING.SHADOW_BATTLEAXE.USES = 250
TUNING.SHADOW_BATTLEAXE.DAMAGE = 48
for i = 1,4 do 
    TUNING.SHADOW_BATTLEAXE.LEVEL[i].LIFE_STEAL = 3.4*(i-1)
    TUNING.SHADOW_BATTLEAXE.LEVEL[i].PLANAR_DAMAGE = 10 + 7*(i-1)

end


TUNING.SHADOWTHRALL_PARASITE_TARGET_DIST = 18

--模组新增常量
local newconstant_tuning = 
{   

    MINOTAUR_STUNTIME = 25,
    --真武器
    TRUE_SWORD_LUNARPLANT_DAMAGE = 50,
    TRUE_SWORD_LUNARPLANT_PLANRDAMAGE = 35,
    TRUE_STAFF_EXPLOSIVE = 50,
    TRUE_WEAPON_USES = 250,
    TRUE_STAFF_BOUNCES = 6,
    TRUE_STAFF_SETBONUS_BOUNCES = 10,

    --死亡收割
    DEATH_HUNTER_HARVEST_RADIUS = 7,

    --黑曜石长矛
    OBSIDIAN_SPEAR_USES = 250,
    OBSIDIAN_SPEAR_DAMAGE = 51,

    --黑曜石甲
    ARMOROBSIDIAN = 950,
    ARMOROBSIDIAN_ABSORPTION = 0.85,

    --火山法杖
    STAFF_OBSIDIAN_DAMAGE = 20,
    STAFF_OBSIDIAN_USES = 100,

    --远古哨塔
    EYETURRET_DAMAGE2 = 75,
    EYETURRET_HEALTH2 = 1500,

    --暗影侦察者
    ANCIENT_SCANNER_HEALTH = 200,

    --龙人
    DRAGOON_HEALTH = 600,
    DRAGOON_DAMAGE = 40,

    --恐惧之龙
    SHAODWDRAGON_HEALTH = 600,
    SHAODWDRAGON_DAMAGE = 50,
    SHAODWDRAGON_FIRECD = 20,
    SHAODWDRAGON_WAVECD = 16,

    --腐化之心
    CORRUPT_HEART_HEALTH = 10000,
    CORRUPT_HEART_RANGESQ = 16*16,
    CORRUPT_HEART_ATTACKRANGE = 400,
    
    --至尊亮茄
    LUNARTHRALL_PLANT_QUEEN_DAMAGE = 120,
    LUNARTHRALL_PLANT_QUEEN_HEALTH = {1800,3000},

    --铁巨人
    ANCIENT_HULK_HEALTH = 18000,

    --附身铠甲
    IRONLORD_HEALTH = 12000,

    ABYSS_CREATURE_TARGET_DIST = 25,
    ABYSS_SHIELD_CD = 50,

    --深渊骑士
    ABYSS_KNIGHT_HEALTH = 3000,
    ABYSS_KNIGHT_DAMAGE = 120,
    ABYSS_KNIGHT_MELEE_RANGE = 5,
    ABYSS_KNIGHT_HIDE_CD  = 20,
    ABYSS_KNIGHT_SPIN_CD = 15,
    

    --远古先驱
    ABYSS_THRALL_HEALTH = 3500,
    ABYSS_THRALL_DAMAGE = 200,
    ABYSS_THRALL_CD = 20,


    --绝望石融合暗影再生
    ABYSS_FISSURE = {
        REGEN_TIME =  4*total_day_time,
        SPAWN_TIME = 60,
    },

    LASERWORKER_USES = 600,

    --资源再生
    ABYSS_GROWTH_FREQUENCY = 8*total_day_time,
    ABYSS_GROWTH_FREQUENCY_VARIANCE = 2*total_day_time,
    ABYSS_FLOWER_REGROWTH = 8*total_day_time,
    ABYSS_RIFT_REPOWER = 15*total_day_time,

    DREADSWORD = {
        USES = 200,
        DAMAGE = 40,
        PLANAR_DAMAGE = 30,
    },

    SWORD_DREADSTONE_REGEN_MAXRATE = 0.01/8,
    SWORD_DREADSTONE_REGEN_MINRATE = 0.01/12,

    BOSSRUSH_CD = 10*total_day_time,

    CALAMITA_HEALTH = 100000,

    LASERCANNON_FUEL = 10*total_day_time,

    ---深渊铁卫
    ABYSS_HOPLITE_HEALTH = 1200,
    ABYSS_HOPLITE_DAMAGE = 75,
    

    --暗能量
    DARK_ENERGY_HEALTH = 1600,

    ABYSS_WORMREGEN = 10*total_day_time,
    ABYSS_THRALLGEN = 10*total_day_time,

    --蝎子
    VOID_PEGHOOKHEALTH = 1200,
}

for k, v in pairs(newconstant_tuning) do
    TUNING[k] = v
end



